config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'
  get 'mapping' => 'mapping#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

    # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

    # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/mapping_controller.rb
class MappingController < ApplicationController
	def index
    @entry = Entry.all

  end
  
  def show
    #@entry = Entry.find(params[:field_name])
  end

  def new
    @entry = Entry.new
  end

  def create
    flash[:notice] =  'Article'
    @entry = Entry.new(db1_params)
   # @db2 = Db2.new(params[:db2])
    if params[:add_field1] 
      flash[:notice] = "hi!"
      @entry.field1s.build
    elsif params[:remove_field1]
      # nested model
    else  
      # save goes like usual
      if @entry.save
        flash[:notice] = "Successfully saved."
      end
    end
    render :action => 'index'   
  end
   
  def edit
    @entry = Entry.find(params[:id])
    if params[:add_field1]
      # rebuild the field1 attributes that doesn't have an id
      unless params[:db1][:field1s_attributes].blank?
        for attribute in params[:db1][:field1s_attributes]
          @entry.field1s.build(attribute.last.except(:_destroy)) unless attribute.last.has_key?(:id)
	end
      end
    @entry.field1s.build 
    end
  end

  def update
   #@entry = Entry.find(params[:id])
   #if params[:add_field1]
   #  unless params[:db1][:fields1_attributes].blank?
   #    for attribute in params[:db1][:field1s_attributes]
   #      @entry.field1s.build(attribute.last.except(:_destory) unless attribute.last.has_key?(:id)
   #    end
   #  end
   #@entry.field1s.build

  end 
  
  private
    def entry_params
      params.require(:db1).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    if session[:user_id] != @user.id
        flash[:success] = "You are not authorized to view this page!"
        redirect_to help_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
    	flash[:success] = "Welcome to the Infoready MDP App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  	def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
#Returns the title of the page
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Infoready MDP Application"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/mapping_helper.rb
module MappingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "img-circular")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.infoready4.com/"></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Mapping Tool", mapping_path %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/mapping/new.html.erb
<% provide(:title, "Select") %>
<h1> Select Data </h1>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
<%= form_for :entry do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :data_source_name %> 
  </p>

  <h3> Fields for Datasource1 </h3>
  <%= f.fields_for :entry do |g| %>
    <p>  
      <%= g.text_field :field_name %>
      <%= g.select :field_type, ['CHAR', 'INTEGER'] %>
      <%= g.check_box :_destroy %>
      <%= g.label :_destroy, 'delete' %>
    </p>
  <% end %>

</div>

<div class="col-sm-6">
<%= form_for :entry do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :data_source_name %> 
  </p>

  <h3> Fields for Datasource1 </h3>
  <%= f.fields_for :entry do |g| %>
    <p>  
      <%= g.text_field :field_name %>
      <%= g.select :field_type, ['CHAR', 'INTEGER'] %>
      <%= g.check_box :_destroy %>
      <%= g.label :_destroy, 'delete' %>
    </p>
  <% end %>
  <% end %>
</div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
  <p>
    <%= f.submit 'Add field', :name => "add_field1" %>
    <%= f.submit 'Delete checked field', :name=> "remove_field1" %>
    <%= f.submit %>  
  </p>
  <% end %>
</div>
</div>
</div>


  

app/views/mapping/show.html.erb
<p> Hi this is a test </p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
  </tbody>
</table>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
	<h1>Sample</h1>
	<body>
		<p>
			This is a placeholder About page for our MDP project
		</p>
	</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Infoready MDP team at MDP-InfoReady2015@umich.edu.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
	<h1>Error</h1>
	<body>
		<p>
			You have been redirected to this page because the page doesn't exist, or you don't have access to the page.
		</p>
	</body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Infoready's MDP Application</h1>

  <h2>
    This is the home page.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("InfoReady.jpg", alt: "infoready logo", size: "200x100"),
            'http://infoready4.com/'%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>